name: hdpmt

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - astropy
  - pytest-astropy
  - pytest-sugar
  - pip
  - pip:
    - streamlit
